project:
  type: website
  output-dir: docs

website:
  title: "Chad Bustard"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: file-text
        href: Resume_ChadBustard.pdf
        text: Resume/CV
      - icon: github
        href: https://github.com/bustardchad
        text: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/chad-bustard-phd-20628090/
        text: LinkedIn
      - icon: files
        href: https://ui.adsabs.harvard.edu/search/fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=database%3A%20(astronomy%20OR%20physics)&q=author%3A(%22Bustard%2C%20Chad%22)&sort=citation_count%20desc%2C%20bibcode%20desc&p_=0  
        text: Publications
      - icon: envelope
        href: mailto:bustardchad@gmail.com
        text: Email
format:
  html:
    theme: cosmo
    css: styles.css





